application:
  port: 8080
  host: "localhost"
  body_limit: "25mib"
  secret: "123"
  ipv4: false

auth:
  # in hour
  lifespan: 168
  cookie_name: session
  # in days
  cookie_max_age: 365
  cookie_http_only: true
  cookie_secure: false
  # in days
  max_lifespan: 365

log:
  dev: true

database:
  user: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  name: "dev"
  timeout: 20

git:
  auth: true
  base: "./src/git-repo"

build:
  max: 2
  # in microseconds (100ms === 1 CPU allocation)
  cpu_ms: 100000
  # in miliseconds
  timeout: 120000
