application:
  port: 8080
  host: "localhost"
  bodylimit: "25mib"
  ipv4: false

auth:
  sso: true
  # in hour
  lifespan: 168
  cookiename: session
  # in days
  maxage: 365
  httponly: true
  secure: false
  # in days
  maxlifespan: 365

log:
  dev: true

database:
  user: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  name: "dev"
  timeout: 20

git:
  auth: true
  base: "./git-repo"

build:
  max: 2
  # in microseconds (100ms === 1 CPU allocation)
  cpums: 100000
  # in miliseconds
  timeout: 120000

container:
  cpu: 0.5
  # amount of swap = memory_swap - memory_limit
  memory: 256M
  swap: 320M
