application:
  port: 8080
  host: "localhost"
  body_limit: "25mib"
  secret: "123"
  auth: true
  ipv4: false
database:
  user: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  name: "dev"
  timeout: 20
git:
  base: "./src/git-repo"
db_proxy:
  host: "localhost"
  port: 5432
