application:
  port: 8080
  host: "localhost"
  body_limit: "25mib"
  secret: "123"
  ipv4: false

auth:
  git: true
  # in hour
  lifespan: 168
  cookie_name: session
  # in days
  cookie_max_age: 365
  cookie_http_only: true
  cookie_secure: false
  # in days
  max_lifespan: 365

database:
  user: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  name: "dev"
  timeout: 20

git:
  base: "./src/git-repo"

builder:
  max_concurrent_builds: 2
  build_timeout: 120000