apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  access: proxy
  editable: true
  isDefault: true
  
    #basicAuth: true
    #basicAuthUser: chef
    #basicAuthPassword: "strong-powerful-password"
