global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    basic_auth:
      username: chef
      password: strong-powerful-password
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['localhost:9113']

  - job_name: 'docker'
    static_configs:
      # - targets: ['localhost:9323']
      - targets: ['docker-host:9323']
